# Generated by Django 5.0.1 on 2024-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='showfour',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='showone',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='showthree',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='showtwo',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
