# Generated by Django 5.0.1 on 2024-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0002_portfolio_showfour_portfolio_showone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
