# Generated by Django 5.0.1 on 2024-01-18 10:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0004_portfolio_showeight_portfolio_showfive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='text_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000),
        ),
    ]
