# Generated by Django 5.0.1 on 2024-01-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0005_alter_portfolio_text_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
