# Generated by Django 5.0.1 on 2024-01-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0006_portfolio_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='loom_video',
            field=models.TextField(blank=True),
        ),
    ]
