# Generated by Django 5.0.1 on 2024-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0007_portfolio_loom_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='loom_video',
            field=models.URLField(blank=True),
        ),
    ]
