# Generated by Django 5.0.1 on 2024-01-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0008_alter_portfolio_loom_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='showeight',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showfive',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showfour',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showseven',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showsix',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showthree',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='showtwo',
        ),
    ]
