# Generated by Django 5.0.1 on 2024-01-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0009_remove_portfolio_showeight_remove_portfolio_showfive_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='portfolo',
        ),
    ]
