# Generated by Django 5.0.1 on 2024-02-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0010_rename_portfolio_portfolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolo',
            old_name='showone',
            new_name='profileimage',
        ),
    ]
