# Generated by Django 5.0.1 on 2024-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0011_rename_showone_portfolo_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolo',
            name='profileimage',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
