# Generated by Django 5.0.1 on 2024-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0012_alter_portfolo_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolo',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
