# Generated by Django 5.0.1 on 2024-03-03 12:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000),
        ),
    ]
