# Generated by Django 5.0.1 on 2024-03-17 16:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0016_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='portfolo',
            name='text_info',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=3000),
        ),
    ]
