# Generated by Django 5.0.1 on 2024-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0017_alter_blog_content_alter_portfolo_text_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Marouan Kaboul', max_length=90),
        ),
    ]
