# Generated by Django 5.0.1 on 2024-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0018_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_modified',
            field=models.CharField(default='january', max_length=90),
        ),
        migrations.AddField(
            model_name='portfolo',
            name='last_modified',
            field=models.CharField(default='january', max_length=90),
        ),
    ]
