# Generated by Django 5.0.1 on 2024-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0019_blog_last_modified_portfolo_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='adawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('h1_title', models.CharField(max_length=150)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('meta_description', models.CharField(max_length=200)),
                ('blogimage', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='portfolo',
            name='last_modified',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
