# Generated by Django 5.0.1 on 2024-04-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patagonia', '0020_adawat_alter_blog_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adawat',
            old_name='blogimage',
            new_name='adatimage',
        ),
    ]
